drop table if exists ANIMALS;
drop table if exists TYPE_MOVEMENT;

create table ANIMALS
(
   id int generated by default as identity (start with 1) primary key,
   name varchar(255) not null,
   type integer not null,
   movement integer not null,
   primary key(id)
);

create table TYPE_MOVEMENT
(
   id int generated by default as identity (start with 1) primary key,
   type varchar(255) not null,
   movement varchar(255) not null,
   primary key(id)
);


insert into TYPE_MOVEMENT  (id,type,movement)  values (1,'Bird','Fly');
insert into TYPE_MOVEMENT  (id,type,movement)  values (2,'Fish','Swim');
insert into TYPE_MOVEMENT  (id,type,movement)  values (3,'Human','Walk');
insert into TYPE_MOVEMENT  (id,type,movement)  values (4,'Snake','Slither');
insert into TYPE_MOVEMENT  (id,type,movement)  values (5,'Kangaroo','Hop');